
@host = http://localhost:3000

GET {{host}}/ http/1.1



###
POST {{host}}/post http/1.1
Content-Type: application/json

{
"firstName":"Olajide",
"lastName":"Macbeth",
"email":"olajidemichael@yahoo.com",
"favoriteColor":"Green",
"birthday":"2004-4-12"
}


###
DELETE {{host}}/delete/6382a5c83ebb7dfb4c2945a0 http/1.1


###
PUT {{host}}/post/637ff78fa11b2dcc87546e39 http/1.1
Content-Type: application/json

{
"firstName":"jide"
    }



